api_id:  26213162  # This has to be an integer. Read more [here](https://core.telegram.org/api/obtaining_api_id)
api_hash: '9e0fa674f494q231eeb13b196718f5e6' # Long 32 characters hash identifier. Read more [here](https://core.telegram.org/api/obtaining_api_id)
session_name: 'setorder' # Session name. Only one session (with a unique session name) can run at a time

# The channel names that you'd like to forward messages from.
# The user running the client must have these channels present on it's dialogs.
input_channel_names:
  - 'news'

# The output channel names that the messages will be forwarded to.
# The user running the client must have a write access to those channels, and have the channels present on theirs dialogs.
# may be multiple
output_channel_names: 
  - 'invest'

# The channel IDs that you'd like to forward messages from. (You can get a channel ID by forwarding any message from it to @userinfobot , and removing the -100 from the start )
input_channel_ids:
  - 2190617475

# The output channel IDs that the messages will be forwarded to. (You can get a channel ID by forwarding any message from it to @userinfobot , and removing the -100 from the start )
output_channel_ids: 
  - 2360215937

# An empty list should be set like this: 
# input_channel_ids: []