# This is a basic workflow that is manually triggered

name: Set order bot

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout code
      uses: actions/checkout@v4.1.7
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Display Python version
      run: python3 -c "import sys; print(sys.version)"
    - name: install dependencies
      run: python3 -m pip install -r requirements.txt
    - name: run bot
      run: source .env | python3 -u main.py config.yml
